//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vuz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> Children { get; set; }
        public int GenderId { get; set; }
        public int Age { get; set; }
        public string StipendReason { get; set; }
        public Nullable<int> StipendSize { get; set; }
        public Nullable<int> FacultyId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
