//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vuz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.ScientificDirections = new HashSet<ScientificDirection>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public int CategoryId { get; set; }
        public int DepartmentId { get; set; }
        public int AcademicRanksId { get; set; }
        public int CountChildren { get; set; }
        public int GenderId { get; set; }
        public int Salary { get; set; }
        public string Aspirant { get; set; }
        public string ScWordks { get; set; }
        public Nullable<int> ScTopicsId { get; set; }
    
        public virtual AcademicRank AcademicRank { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificDirection> ScientificDirections { get; set; }
        public virtual ScientificTopic ScientificTopic { get; set; }
    }
}
